### ISSUE TITLE
Decentralized Exchange Examples

### ISSUE THREAD

**Issue by Sentient-XII** [SunWeb3Sec/DeFiLabs#1]
Please include a dex like GMX  (place a trade, increase position, decrease position, liquidated) for example. 

great learning resources man!

**Comment by SunWeb3Sec** [comment]
Hey, We need these kinds of sample codes to accelerate our testing/debugging, etc.

If you have time, feel free to add any test cases.  

We need more contributors to jump in. XD
@eugenioclrc will cover uniswap.

**Comment by Sentient-XII** [comment]
Okay, let me work on few test cases following your examples

**Comment by eugenioclrc** [comment]
hey @NewCoNam i will be adding some uniswapV2 examples, you could go with V3
